template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "halh1238"
__REPO__ = "lang-khk"
__UND2C__ = "khk"
__UNDEFINED__ = "Halh Mongolian"
__UND__ = "khk"
