template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "halh1238"
__REPO__ = "lang-khk"
__UND2C__ = "khk"
__UNDEFINED__ = "Halh Mongolian"
__UND__ = "khk"
