template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "halh1238"
__REPO__ = "lang-khk"
__UND2C__ = "khk"
__UNDEFINED__ = "Halh Mongolian"
__UND__ = "khk"
